### ISSUE TITLE
Card payment - invalid checksum

### ISSUE THREAD

**Issue by pszalko** [tpay-com/omnipay-tpay#12]
We have the following issue with the latest code (commit: `656b670ad09b16022fc6ca863b5beb00553e7da6`).
Maybe something has changed on server side? @piotrjozwiak 

```
Omnipay\Tpay\_class_tpay\Utilities\TException
0 : Card payment - invalid checksum. in file /webapps/vendor/omnipay/tpay/src/_class_tpay/PaymentCard.php line: 110
```

The above error points to the following lines:

```
        $hash = hash($this->cardHashAlg, $sale . $testMode . $saleAuth . $this->orderID . $this->clientAuthCode .
            $card . $this->currency . $this->amount . $saleDate . $status . $reason . $this->cardVerificationCode);
        if ($sign !== $hash) {
            throw new TException('Card payment - invalid checksum.');
        }
```

Here are the request details in case you would like to find at your system:

param | value
-- | --
amount | 1
card | ****9891
currency | 985
date | 2021-10-07 14:33:35
order_id | 835
sale_auth | [Filtered]
sign | de2eff1ba3fbbd6d28ca39611b16151d1b0675e522dcc7a321ad1070bb6e7dbf004bd816c335b9a2ce45eead664b54f330037975f333e4fc61efc9dc5c1e33d7
status | correct
type | sale

Please verify if there is need for update.

**Comment by piotrjozwiak** [comment]
Hi @pszalko 
We have just resolved the mentioned issue https://github.com/tpay-com/omnipay-tpay/pull/13
