### ISSUE TITLE
Add dependency to tpay-com/tpay-php

### ISSUE THREAD

**Issue by pszalko** [tpay-com/omnipay-tpay#2]
Since `src/_class_tpay`directory is duplicated from [tpay-com/tpay-php project](https://github.com/tpay-com/tpay-php), maybe it is worth adding it as dependency in `composer.json` instead of copying between repos?

I can see that current implementation is at least incomplete or out of sync from `tpay-php` lib.

For example: `ObjectsHelper` class has the following implementation of the `requests()` method:
```
    public function requests($url, $params)
    {
        return false;
    }
```
while the same method in `tpay-lib` looks as follow:
```
    public function requests($url, $params)
    {
        $this->curl = new Curl();
        return $this->curl->setRequestUrl($url)
            ->setPostData($params)
            ->enableJSONResponse()
            ->doRequest()
            ->getResult();
    }
```

Is this inconsistency by design, or is it a bug?

**Comment by piotrjozwiak** [comment]
A lot of content has been removed from the library because it will not be used anytime.
We had to redesign some functions to keep their definitions compatible with omnipay structure. The example function you provided is changed because omnipay library uses guzzle to make requests.

**Comment by pszalko** [comment]
Is it possible to use this library to make other requests than `secure sale`?

**Comment by piotrjozwiak** [comment]
Of course, we have handled almost all omnipay functions with our API requests according to docs.tpay.com documentation.
Here is the list:
- Authorize -> [presale](https://docs.tpay.com/#!/Cards_API/post_api_cards_api_key_presale)
- Capture -> [sale](https://docs.tpay.com/#!/Cards_API/post_api_cards_api_key_sale)
- Purchase -> [securesale](https://docs.tpay.com/#!/Cards_API/post_api_cards_api_key_securesale)
- completePurchase -> [consume notification at your endpoint](https://docs.tpay.com/#!/Tpay/tpay_elavon_notifications)
- deleteCard -> [deregister](https://docs.tpay.com/#!/Cards_API/post_api_cards_api_key_deregister)
- refund -> [refund](https://docs.tpay.com/#!/Cards_API/post_api_cards_api_key_refund)

**Comment by pszalko** [comment]
Thanks for quick reply!

However, I've tried to make `Authorize` / `presale` request, and found out that I need to have `cli_auth` param value. As far as I understand to get `cli_auth` value I need to make [register sale](https://docs.tpay.com/#!/Cards_API/post_api_cards_api_key_register_sale) request, but it was not possible in current implementation.

How to get `cli_auth` param? Or how to make `presale` request using omnipay interface?

**Comment by piotrjozwiak** [comment]
The secure sale method also returns client token parameter "cli_auth". Please read our [documentation](https://docs.tpay.com/#!/Cards_API/post_api_cards_api_key_securesale) The way of returning this parameter depends on 3D Secure protection of credit card.
This articles can also be very useful to understand this process
- [recurring payments](https://support.tpay.com/en/faq/recurring-payments-without-user-intervention)
- [credit card validation process](https://support.tpay.com/en/faq/is-it-possible-to-validate-card-information-immediatelly)

**Comment by pszalko** [comment]
Thank you for the links, they are really helpful, since documentation was not clear enough about the process.
