### ISSUE TITLE
Unable to delete (deregister) card

### ISSUE THREAD

**Issue by pszalko** [tpay-com/omnipay-tpay#4]
I am not able to deregister card, because of the following exception: 
`The cli_auth parameter is required`

The code used to deregister card is as follow:

```
$deleteCardRequest = $gateway->deleteCard($_POST);
$tpayResponse = $deleteCardRequest->getData();
```

It looks like the `cli_auth` param is not read correctly from tpay notification payload, neither directly nor from params given to `deleteCard()` method.

The POST data:
```
Array (
[type] => deregister
[test_mode] => 1
[cli_auth] => t5a9d52f5d82da88a36f4984c59816ef86827dcd
[date] => 2018-03-05 15:25:41
[sign] => d1a966903cd2c1b3bcd2677bdb71666352ea75b9c1492ac90f6b898b4c5c543bf83371b0b36e9e4ec0aca1ba33fd041b1a66e977f77bd0d076e1a0324e7f9c7f 
)
```

**Comment by piotrjozwiak** [comment]
You should use setToken method before sending deregister request.
Please see the following examples:
Setting a token from purchase response data (non-3DS credit card):

$purchaseResponse = $gateway
    ->purchase($params)
    ->setDescription("payment for order xyz")
    ->setAmount(10.00)
    ->setCurrency('PLN')
    ->setOrderId(32145)
    ->setCardSave()
    ->send();
if ($purchaseResponse->isPaid()) {
    $token = $purchaseResponse->getToken();
    $deregisterResponse = $gateway
        ->deleteCard($params)
        ->setToken($token)
        ->send();
    var_dump($deregisterResponse->isSuccessful());
}

Settign a token from notification (3DS protected credit card):

$deregisterResponse = $gateway
    ->deleteCard($params)
    ->setToken($_POST['cli_auth'])
    ->send();
var_dump($deregisterResponse->isSuccessful());

or

$completePurchaseResponse = $gateway->completePurchase(array())
        ->setAmount(10.00)
        ->setCurrency('PLN')
        ->setOrderId(32145)
        ->getData();
$deregisterResponse = $gateway
    ->deleteCard($params)
    ->setToken($completePurchaseResponse['cli_auth'])
    ->send();
var_dump($deregisterResponse->isSuccessful());

Where $params is an array containing CreditCard object initialised like:
`$params = array('card' => new CreditCard($formInputData));`

**Comment by pszalko** [comment]
Thanks @piotrjozwiak, your comment clears a lot.

However, I think it's not clear from documentation nor from examples how to deregister card with tpay library. I would suggest to write it in documentation for further users.

**Comment by piotrjozwiak** [comment]
@pszalko sure, I will make some updates :)

**Comment by miwsio** [comment]
Hello, is there any complete example for just deregister card?
