### ISSUE TITLE
test_mode

### ISSUE THREAD

**Issue by beaceberq** [tpay-com/omnipay-tpay#6]
Is the test_mode parameter ever sent ?
I set test_model = 1 according to the documentation but I do not see it being sent to the tpay server

> POST /api/cards/*** HTTP/1.1
Host: secure.tpay.com
Content-Length: 783
User-Agent: Guzzle/3.9.3 curl/7.38.0 PHP/5.6.33-0+deb8u1
Content-Type: application/x-www-form-urlencoded; charset=utf-8
method=securesale
&card=****
&name=Jan%20Kowalski
&email=****
&desc=****
&amount=1.00
&currency=985
&order_id=31
&onetimer=1
&language=pl
&enable_pow_url=1
&sign=***
&pow_url=***
&pow_url_blad=****
&api_password=****
&json=1

**Comment by piotrjozwiak** [comment]
@beaceberq we do not use "test_mode" parameter in outgoing requests body. Tpay.com system emulates test mode by switching your API between test and production mode, so if you are in test mode, every request you make is treated like test request.

This parameter will be returned in response or notification from Tpay, to avoid booking payment like production payment by mistake.

If you would like to switch between API production and the test mode, you can contact our support team at pt@tpay.com email.
