### ISSUE TITLE
Update hashing algorithm

### ISSUE THREAD

**Issue by pszalko** [tpay-com/omnipay-tpay#9]
Please update hashing algorithm to the latest version according to docs: https://support.tpay.com/pl/aktualizacja-sposobu-liczenia-sumy-kontrolnej

@piotrjozwiak I have created PR #8 - please merge it before deadline at 20.07.2021

**Comment by piotrjozwiak** [comment]
@pszalko thank you for participation. The PR has been merged.

**Comment by pszalko** [comment]
<img width="919" alt="Screenshot 2021-07-19 at 14 33 10" src="https://user-images.githubusercontent.com/345640/126162729-19a173c3-6445-4219-a4f2-8c1dca0cddc9.png">

After updating hashing algorithm TPay throws exception "invalid checksum". 
@piotrjozwiak Could you verify if server sends correct notification? Here is POST data we've received:
```
amount=1195.65&card=%2A%2A%2A%2A0615&currency=985&date=2021-07-19%2013%3A20%3A04&order_id=803&sale_auth=%5BFiltered%5D&sign=ddd29d69407f414e6345b7dde6a09c483a59fa659d8067811be6b155ccb1a9fd5731022407b6dc846ea916964e332fc4aa8cc7ac586c9da0a35301f28ef936ac&status=correct&type=sale
```

**Comment by piotrjozwiak** [comment]
@pszalko I have rolled back changes to method calculating hash while handling card payment notifications https://github.com/tpay-com/omnipay-tpay/commit/656b670ad09b16022fc6ca863b5beb00553e7da6
The hash update was required only when sending to Tpay, not when receiving notifications.

**Comment by pszalko** [comment]
@piotrjozwiak  Thanks! I didn't catch that in docs. So now the code is up to date with the latest changes in TPay API?

**Comment by piotrjozwiak** [comment]
Yes, the code is up to date :)
